In [108]:
import pandas as pd
import numpy as nd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import accuracy_score

In [109]:
df=pd.read_csv('project_I.csv')
df

id        product  recommended                              shop  \
0          295  8270579663139         True  shopcast-stage-1-0.myshopify.com   
1          228  8270579335459         True  shopcast-stage-1-0.myshopify.com   
2          279  8270579335459         True  shopcast-stage-1-0.myshopify.com   
3          231  8270579269923         True  shopcast-stage-1-0.myshopify.com   
4          235  8270579335459         True  shopcast-stage-1-0.myshopify.com   
...        ...            ...          ...                               ...   
4995  16131932  6877473243254        False           shoeboxpk.myshopify.com   
4996  16143424  6842053886070        False           shoeboxpk.myshopify.com   
4997  16132540  6691491545206        False           shoeboxpk.myshopify.com   
4998  16144720  6842050576502        False           shoeboxpk.myshopify.com   
4999  16133740  6802311577718        False           shoeboxpk.myshopify.com   

               uid                           api_key  email  order_id  \
0     kM7u3GN9Qqme  015629919a40414db823561bddb1e8e3    NaN       NaN   
1     Ue66GQ3Hp5Ha  015629919a40414db823561bddb1e8e3    NaN       NaN   
2     kM7u3GN9Qqme  015629919a40414db823561bddb1e8e3    NaN       NaN   
3     Ue66GQ3Hp5Ha  015629919a40414db823561bddb1e8e3    NaN       NaN   
4     Ue66GQ3Hp5Ha  015629919a40414db823561bddb1e8e3    NaN       NaN   
...            ...                               ...    ...       ...   
4995  sxsPnVSyArUr  12373fcff2284a409d56bcbe7c4a1ea1    NaN       NaN   
4996  np7qVDz6fGLJ  12373fcff2284a409d56bcbe7c4a1ea1    NaN       NaN   
4997  AHla2f2pDC4-  12373fcff2284a409d56bcbe7c4a1ea1    NaN       NaN   
4998  cNt-6b0ntESD  12373fcff2284a409d56bcbe7c4a1ea1    NaN       NaN   
4999  YP_MKKF_MIBc  12373fcff2284a409d56bcbe7c4a1ea1    NaN       NaN   

               created_at   device     price  
0     2023-08-18 13:45:54  desktop    2490.0  
1     2023-08-16 12:59:52  desktop  960000.0  
2     2023-08-18 07:29:15  desktop  960000.0  
3     2023-08-16 12:52:55  desktop    1024.0  
4     2023-08-16 12:54:08  desktop  960000.0  
...                   ...      ...       ...  
4995  2023-09-20 06:33:46   mobile       NaN  
4996  2023-09-20 06:38:39   mobile       NaN  
4997  2023-09-20 06:34:01  desktop       NaN  
4998  2023-09-20 06:39:09   mobile       NaN  
4999  2023-09-20 06:34:31   mobile       NaN  

[5000 rows x 11 columns]

In [110]:

df=df.drop(columns={'shop','email','order_id','created_at','device','price','api_key','recommended','id'})

In [111]:
df

product           uid
0     8270579663139  kM7u3GN9Qqme
1     8270579335459  Ue66GQ3Hp5Ha
2     8270579335459  kM7u3GN9Qqme
3     8270579269923  Ue66GQ3Hp5Ha
4     8270579335459  Ue66GQ3Hp5Ha
...             ...           ...
4995  6877473243254  sxsPnVSyArUr
4996  6842053886070  np7qVDz6fGLJ
4997  6691491545206  AHla2f2pDC4-
4998  6842050576502  cNt-6b0ntESD
4999  6802311577718  YP_MKKF_MIBc

[5000 rows x 2 columns]

In [112]:
encoded_df=pd.get_dummies(df,columns=['product'],dtype=int)
encoded_df

uid  product_2617304088694  product_3880595226742  \
0     kM7u3GN9Qqme                      0                      0   
1     Ue66GQ3Hp5Ha                      0                      0   
2     kM7u3GN9Qqme                      0                      0   
3     Ue66GQ3Hp5Ha                      0                      0   
4     Ue66GQ3Hp5Ha                      0                      0   
...            ...                    ...                    ...   
4995  sxsPnVSyArUr                      0                      0   
4996  np7qVDz6fGLJ                      0                      0   
4997  AHla2f2pDC4-                      0                      0   
4998  cNt-6b0ntESD                      0                      0   
4999  YP_MKKF_MIBc                      0                      0   

      product_3880595259510  product_4408323145846  product_4408330223734  \
0                         0                      0                      0   
1                         0                      0                      0   
2                         0                      0                      0   
3                         0                      0                      0   
4                         0                      0                      0   
...                     ...                    ...                    ...   
4995                      0                      0                      0   
4996                      0                      0                      0   
4997                      0                      0                      0   
4998                      0                      0                      0   
4999                      0                      0                      0   

      product_4408330289270  product_4408330748022  product_4408330813558  \
0                         0                      0                      0   
1                         0                      0                      0   
2                         0                      0                      0   
3                         0                      0                      0   
4                         0                      0                      0   
...                     ...                    ...                    ...   
4995                      0                      0                      0   
4996                      0                      0                      0   
4997                      0                      0                      0   
4998                      0                      0                      0   
4999                      0                      0                      0   

      product_4416592281718  ...  product_8270569537827  \
0                         0  ...                      0   
1                         0  ...                      0   
2                         0  ...                      0   
3                         0  ...                      0   
4                         0  ...                      0   
...                     ...  ...                    ...   
4995                      0  ...                      0   
4996                      0  ...                      0   
4997                      0  ...                      0   
4998                      0  ...                      0   
4999                      0  ...                      0   

      product_8270570750243  product_8270573175075  product_8270579269923  \
0                         0                      0                      0   
1                         0                      0                      0   
2                         0                      0                      0   
3                         0                      0                      1   
4                         0                      0                      0   
...                     ...                    ...                    ...   
4995                      0                      0                      0   
4996                   

In [113]:
ab=encoded_df.groupby('uid').agg('sum').iloc[:,10:]
ab

product_4470759391350  product_4470759424118  \
uid                                                          
--HmgGZN-V-C                      0                      0   
-2he5U_l1TLY                      0                      0   
-3pyOXldrSof                      0                      0   
-4nwgjoDmzkC                      0                      0   
-7ujn5GMHO2D                      0                      0   
...                             ...                    ...   
zwz57K0RDy_p                      0                      0   
zxbrFZ4xL9Hd                      0                      0   
zyM0hO9_Ha6K                      0                      0   
zzTBRzQcw_z0                      0                      0   
zzvxlIQ0360A                      0                      0   

              product_4470759686262  product_4470759784566  \
uid                                                          
--HmgGZN-V-C                      0                      0   
-2he5U_l1TLY                      0                      0   
-3pyOXldrSof                      0                      0   
-4nwgjoDmzkC                      0                      0   
-7ujn5GMHO2D                      0                      0   
...                             ...                    ...   
zwz57K0RDy_p                      0                      0   
zxbrFZ4xL9Hd                      0                      0   
zyM0hO9_Ha6K                      0                      0   
zzTBRzQcw_z0                      0                      0   
zzvxlIQ0360A                      0                      0   

              product_4470759981174  product_6535232815222  \
uid                                                          
--HmgGZN-V-C                      0                      0   
-2he5U_l1TLY                      0                      0   
-3pyOXldrSof                      0                      0   
-4nwgjoDmzkC                      0                      0   
-7ujn5GMHO2D                      0                      0   
...                             ...                    ...   
zwz57K0RDy_p                      0                      0   
zxbrFZ4xL9Hd                      0                      0   
zyM0hO9_Ha6K                      0                      0   
zzTBRzQcw_z0                      0                      0   
zzvxlIQ0360A                      0                      0   

              product_6535232847990  product_6537374400630  \
uid                                                          
--HmgGZN-V-C                      0                      0   
-2he5U_l1TLY                      0                      0   
-3pyOXldrSof                      0                      0   
-4nwgjoDmzkC                      0                      0   
-7ujn5GMHO2D                      0                      0   
...                             ...                    ...   
zwz57K0RDy_p                      0                      0   
zxbrFZ4xL9Hd                      0                      0   
zyM0hO9_Ha6K                      0                      0   
zzTBRzQcw_z0                      0                      0   
zzvxlIQ0360A                      0                      0   

              product_6537375088758  product_6537375907958  ...  \
uid                                                         ...   
--HmgGZN-V-C                      0                      0  ...   
-2he5U_l1TLY                      0                      0  ...   
-3pyOXldrSof                      0                      0  ...   
-4nwgjoDmzkC                      0                      0  ...   
-7ujn5GMHO2D                      0                      0  ...   
...                             ...                    ...  ...   
zwz57K0RDy_p                      0                      0  ...   
zxbrFZ4xL9Hd                      0                      0  ...   
zyM0hO9_Ha6K                      0                      0  ...   
zzTBRzQcw_z0                      0              

In [114]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import NearestNeighbors
X_train, X_test = train_test_split( ab, test_size=0.003, random_state=42)
knn=NearestNeighbors(n_neighbors=5)
knn.fit(X_train)

NearestNeighbors()

In [115]:
df1=knn.kneighbors(X_test, return_distance=False)
df1

array([[1077, 2585, 1753, 1726, 2067],
       [ 244, 2267, 1862, 1518, 1972],
       [ 471, 2261,  117, 1518, 1972],
       [1456, 1185,  830,  720, 1189],
       [ 931, 1735, 1910, 1647, 1858],
       [ 303, 1747,   91, 1998, 2502],
       [1668, 1798,   92,  161, 2065],
       [2190,  378, 2066, 2438, 1924],
       [2352,  350,  619, 2199,  414]], dtype=int64)

In [116]:
df2=knn.kneighbors(X_train,return_distance=False)
df2

array([[1423,    0, 1686, 1518, 1972],
       [   1, 1871,  406,  422, 1148],
       [   2,  112, 1699, 1752,  666],
       ...,
       [ 262,  461,  551,   54,   36],
       [2539, 1663, 1156, 1927, 1508],
       [ 414, 1518, 1341, 1972, 1862]], dtype=int64)

In [117]:
#for test set
display_test_data=[]
for i in range(len(df1)):
    display(X_test.index[i],df.iloc[df1[i],:][['product']].values)

'UhtCLBFlwBxL'

array([[6618171342966],
       [6882470527094],
       [6641935515766],
       [6845763485814],
       [6802312790134]], dtype=int64)

'RrNbFnns-ePK'

array([[6811309768822],
       [6842051952758],
       [6612902215798],
       [6773254062198],
       [6722005368950]], dtype=int64)

'OshN4OhiUrEP'

array([[6687799935094],
       [6535232847990],
       [6641824399478],
       [6773254062198],
       [6722005368950]], dtype=int64)

'I05FDOknX_Td'

array([[6842052640886],
       [6842053886070],
       [6691490463862],
       [6690173517942],
       [6691490758774]], dtype=int64)

'S5AdOaNmpdO2'

array([[6762888298614],
       [6842053886070],
       [6811309310070],
       [6850090991734],
       [6612902346870]], dtype=int64)

'C15QBK65wVZQ'

array([[6880534659190],
       [6784971767926],
       [6844038840438],
       [6798356381814],
       [6545778147446]], dtype=int64)

'IvmDyEAHJLzr'

array([[6601445441654],
       [6842053132406],
       [6618171211894],
       [6877477109878],
       [6773253898358]], dtype=int64)

'MekJ7DPCPqYi'

array([[6877472424054],
       [6545778147446],
       [6811309310070],
       [6890548166774],
       [6687454560374]], dtype=int64)

'pGp3M25q2sBu'

array([[6882470723702],
       [6880534691958],
       [6691490693238],
       [6678388801654],
       [6690173583478]], dtype=int64)

In [118]:
#for test set
display_test_data=[]
for i in range(len(df1)):
    display_test_data.append(df.iloc[df1[i],:][['product']].values)
display_test_data

[array([[6618171342966],
        [6882470527094],
        [6641935515766],
        [6845763485814],
        [6802312790134]], dtype=int64),
 array([[6811309768822],
        [6842051952758],
        [6612902215798],
        [6773254062198],
        [6722005368950]], dtype=int64),
 array([[6687799935094],
        [6535232847990],
        [6641824399478],
        [6773254062198],
        [6722005368950]], dtype=int64),
 array([[6842052640886],
        [6842053886070],
        [6691490463862],
        [6690173517942],
        [6691490758774]], dtype=int64),
 array([[6762888298614],
        [6842053886070],
        [6811309310070],
        [6850090991734],
        [6612902346870]], dtype=int64),
 array([[6880534659190],
        [6784971767926],
        [6844038840438],
        [6798356381814],
        [6545778147446]], dtype=int64),
 array([[6601445441654],
        [6842053132406],
        [6618171211894],
        [6877477109878],
        [6773253898358]], dtype=int64),
 array([[68774724240

In [119]:
flat_test_data=[]
for arr in display_test_data:
    flattened_arr = [item for sublist in arr for item in sublist] #array flatten
    rows_df = pd.DataFrame([flattened_arr], columns=[f'Recommendation_{i+1}' for i in range(len(flattened_arr))])
    flat_test_data.append(rows_df)


df3 = pd.concat(flat_test_data, ignore_index=True)
print(df3)

   Recommendation_1  Recommendation_2  Recommendation_3  Recommendation_4  \
0     6618171342966     6882470527094     6641935515766     6845763485814   
1     6811309768822     6842051952758     6612902215798     6773254062198   
2     6687799935094     6535232847990     6641824399478     6773254062198   
3     6842052640886     6842053886070     6691490463862     6690173517942   
4     6762888298614     6842053886070     6811309310070     6850090991734   
5     6880534659190     6784971767926     6844038840438     6798356381814   
6     6601445441654     6842053132406     6618171211894     6877477109878   
7     6877472424054     6545778147446     6811309310070     6890548166774   
8     6882470723702     6880534691958     6691490693238     6678388801654   

   Recommendation_5  
0     6802312790134  
1     6722005368950  
2     6722005368950  
3     6691490758774  
4     6612902346870  
5     6545778147446  
6     6773253898358  
7     6687454560374  
8     6690173583478  


In [120]:
df3

Recommendation_1  Recommendation_2  Recommendation_3  Recommendation_4  \
0     6618171342966     6882470527094     6641935515766     6845763485814   
1     6811309768822     6842051952758     6612902215798     6773254062198   
2     6687799935094     6535232847990     6641824399478     6773254062198   
3     6842052640886     6842053886070     6691490463862     6690173517942   
4     6762888298614     6842053886070     6811309310070     6850090991734   
5     6880534659190     6784971767926     6844038840438     6798356381814   
6     6601445441654     6842053132406     6618171211894     6877477109878   
7     6877472424054     6545778147446     6811309310070     6890548166774   
8     6882470723702     6880534691958     6691490693238     6678388801654   

   Recommendation_5  
0     6802312790134  
1     6722005368950  
2     6722005368950  
3     6691490758774  
4     6612902346870  
5     6545778147446  
6     6773253898358  
7     6687454560374  
8     6690173583478

In [121]:
display_train_data=[]
for i in range (len(df2)):
    display_train_data.append(df.iloc[df2[i],:][['product']].values)
display_train_data

[array([[6545780703350],
        [8270579663139],
        [6682258276470],
        [6773254062198],
        [6722005368950]], dtype=int64),
 array([[8270579335459],
        [6612902510710],
        [6590597300342],
        [6682172719222],
        [6890548101238]], dtype=int64),
 array([[8270579335459],
        [6691491872886],
        [6802312298614],
        [6682259193974],
        [6712644501622]], dtype=int64),
 array([[6844039037046],
        [8270579269923],
        [6773254062198],
        [6612902215798],
        [6722005368950]], dtype=int64),
 array([[8270579335459],
        [6722005368950],
        [6682258276470],
        [6612902215798],
        [6690173452406]], dtype=int64),
 array([[8270579269923],
        [6691487711350],
        [6784971800694],
        [6842053623926],
        [6850091352182]], dtype=int64),
 array([[8270569537827],
        [6798854422646],
        [6690173452406],
        [6682258276470],
        [6722005368950]], dtype=int64),
 array([[67838596220

In [122]:
dfp=[]
for arr in display_train_data:
    flattened_arr = [item for sublist in arr for item in sublist] #array flatten
    rows_df = pd.DataFrame([flattened_arr], columns=[f'Recommendation_{i+1}' for i in range(len(flattened_arr))])
    dfp.append(rows_df)


df4 = pd.concat(dfp, ignore_index=True)
print(df4)

      Recommendation_1  Recommendation_2  Recommendation_3  Recommendation_4  \
0        6545780703350     8270579663139     6682258276470     6773254062198   
1        8270579335459     6612902510710     6590597300342     6682172719222   
2        8270579335459     6691491872886     6802312298614     6682259193974   
3        6844039037046     8270579269923     6773254062198     6612902215798   
4        8270579335459     6722005368950     6682258276470     6612902215798   
...                ...               ...               ...               ...   
2685     6802312102006     6691491381366     6691491315830     6882460598390   
2686     6784971898998     6842053918838     6849472954486     6690173681782   
2687     6842053886070     6678387753078     6784971604086     6691491840118   
2688     6850090139766     6881622491254     6802311839862     6682172719222   
2689     6690173583478     6773254062198     6682258276470     6722005368950   

      Recommendation_5  
0        67220

In [123]:
df4

Recommendation_1  Recommendation_2  Recommendation_3  Recommendation_4  \
0        6545780703350     8270579663139     6682258276470     6773254062198   
1        8270579335459     6612902510710     6590597300342     6682172719222   
2        8270579335459     6691491872886     6802312298614     6682259193974   
3        6844039037046     8270579269923     6773254062198     6612902215798   
4        8270579335459     6722005368950     6682258276470     6612902215798   
...                ...               ...               ...               ...   
2685     6802312102006     6691491381366     6691491315830     6882460598390   
2686     6784971898998     6842053918838     6849472954486     6690173681782   
2687     6842053886070     6678387753078     6784971604086     6691491840118   
2688     6850090139766     6881622491254     6802311839862     6682172719222   
2689     6690173583478     6773254062198     6682258276470     6722005368950   

      Recommendation_5  
0        6722005368950  
1        6890548101238  
2        6712644501622  
3        6722005368950  
4        6690173452406  
...                ...  
2685     6635892342902  
2686     6618171015286  
2687     8193723531577  
2688     6849906245750  
2689     6612902215798  

[2690 rows x 5 columns]

In [124]:
X_train_index = X_train.index.values
X_train_index = pd.DataFrame(X_train_index)
X_train_index

0
0     FoHuidhYdhU4
1     YaEjdJg1KURa
2     BJyfksB6fJe3
3     pM3cQKQypV7B
4     Ne15KbCfrR_G
...            ...
2685  b4EYPh_HoUq3
2686  OgCb4syRhMrG
2687  PUXNcLRjyJvW
2688  Tkr9tU5z2GRi
2689  JJ9Ewuj_9W_w

[2690 rows x 1 columns]

In [156]:
df4=df4.set_index(X_train_index[0])
df4

Recommendation_1  Recommendation_2  Recommendation_3  \
0                                                                    
FoHuidhYdhU4     6545780703350     8270579663139     6682258276470   
YaEjdJg1KURa     8270579335459     6612902510710     6590597300342   
BJyfksB6fJe3     8270579335459     6691491872886     6802312298614   
pM3cQKQypV7B     6844039037046     8270579269923     6773254062198   
Ne15KbCfrR_G     8270579335459     6722005368950     6682258276470   
...                        ...               ...               ...   
b4EYPh_HoUq3     6802312102006     6691491381366     6691491315830   
OgCb4syRhMrG     6784971898998     6842053918838     6849472954486   
PUXNcLRjyJvW     6842053886070     6678387753078     6784971604086   
Tkr9tU5z2GRi     6850090139766     6881622491254     6802311839862   
JJ9Ewuj_9W_w     6690173583478     6773254062198     6682258276470   

              Recommendation_4  Recommendation_5  
0                                                 
FoHuidhYdhU4     6773254062198     6722005368950  
YaEjdJg1KURa     6682172719222     6890548101238  
BJyfksB6fJe3     6682259193974     6712644501622  
pM3cQKQypV7B     6612902215798     6722005368950  
Ne15KbCfrR_G     6612902215798     6690173452406  
...                        ...               ...  
b4EYPh_HoUq3     6882460598390     6635892342902  
OgCb4syRhMrG     6690173681782     6618171015286  
PUXNcLRjyJvW     6691491840118     8193723531577  
Tkr9tU5z2GRi     6682172719222     6849906245750  
JJ9Ewuj_9W_w     6722005368950     6612902215798  

[2690 rows x 5 columns]

In [146]:
X_test_index=X_test.index.values
X_test_index=pd.DataFrame(X_test_index)
X_test_index

0
0  UhtCLBFlwBxL
1  RrNbFnns-ePK
2  OshN4OhiUrEP
3  I05FDOknX_Td
4  S5AdOaNmpdO2
5  C15QBK65wVZQ
6  IvmDyEAHJLzr
7  MekJ7DPCPqYi
8  pGp3M25q2sBu

In [154]:
df3=df3.set_index(X_test_index[0])
df3

Recommendation_1  Recommendation_2  Recommendation_3  \
0                                                                    
UhtCLBFlwBxL     6618171342966     6882470527094     6641935515766   
RrNbFnns-ePK     6811309768822     6842051952758     6612902215798   
OshN4OhiUrEP     6687799935094     6535232847990     6641824399478   
I05FDOknX_Td     6842052640886     6842053886070     6691490463862   
S5AdOaNmpdO2     6762888298614     6842053886070     6811309310070   
C15QBK65wVZQ     6880534659190     6784971767926     6844038840438   
IvmDyEAHJLzr     6601445441654     6842053132406     6618171211894   
MekJ7DPCPqYi     6877472424054     6545778147446     6811309310070   
pGp3M25q2sBu     6882470723702     6880534691958     6691490693238   

              Recommendation_4  Recommendation_5  
0                                                 
UhtCLBFlwBxL     6845763485814     6802312790134  
RrNbFnns-ePK     6773254062198     6722005368950  
OshN4OhiUrEP     6773254062198     6722005368950  
I05FDOknX_Td     6690173517942     6691490758774  
S5AdOaNmpdO2     6850090991734     6612902346870  
C15QBK65wVZQ     6798356381814     6545778147446  
IvmDyEAHJLzr     6877477109878     6773253898358  
MekJ7DPCPqYi     6890548166774     6687454560374  
pGp3M25q2sBu     6678388801654     6690173583478

In [161]:
df4=df4.rename_axis('uid')
df3=df3.rename_axis('uid')

In [163]:
df4

Recommendation_1  Recommendation_2  Recommendation_3  \
uid                                                                  
FoHuidhYdhU4     6545780703350     8270579663139     6682258276470   
YaEjdJg1KURa     8270579335459     6612902510710     6590597300342   
BJyfksB6fJe3     8270579335459     6691491872886     6802312298614   
pM3cQKQypV7B     6844039037046     8270579269923     6773254062198   
Ne15KbCfrR_G     8270579335459     6722005368950     6682258276470   
...                        ...               ...               ...   
b4EYPh_HoUq3     6802312102006     6691491381366     6691491315830   
OgCb4syRhMrG     6784971898998     6842053918838     6849472954486   
PUXNcLRjyJvW     6842053886070     6678387753078     6784971604086   
Tkr9tU5z2GRi     6850090139766     6881622491254     6802311839862   
JJ9Ewuj_9W_w     6690173583478     6773254062198     6682258276470   

              Recommendation_4  Recommendation_5  
uid                                               
FoHuidhYdhU4     6773254062198     6722005368950  
YaEjdJg1KURa     6682172719222     6890548101238  
BJyfksB6fJe3     6682259193974     6712644501622  
pM3cQKQypV7B     6612902215798     6722005368950  
Ne15KbCfrR_G     6612902215798     6690173452406  
...                        ...               ...  
b4EYPh_HoUq3     6882460598390     6635892342902  
OgCb4syRhMrG     6690173681782     6618171015286  
PUXNcLRjyJvW     6691491840118     8193723531577  
Tkr9tU5z2GRi     6682172719222     6849906245750  
JJ9Ewuj_9W_w     6722005368950     6612902215798  

[2690 rows x 5 columns]

In [174]:
def take_product_rows(uid,df3,df4):
    values_df3=df3.loc[uid] if uid in df3.index else None
    vlaues_df4=df4.loc[uid] if uid in df4.index else None
    return values_df3,vlaues_df4

def user_input():
    uid=input('Please Write Your UID')
    values_df3,vlaues_df4=take_product_rows(uid,df3,df4)
    if values_df3 is not None:
        print("You may Also Like These Prodcuts:\n",values_df3)
    elif vlaues_df4 is not None:
        print("You may Also Like These Prodcuts:\n",vlaues_df4)
    else:
        print("No products found for UID:", uid, "in database")
user_input()

Please Write Your UID S5AdOaNmpdO2


You may Also Like These Prodcuts:
 Recommendation_1    6762888298614
Recommendation_2    6842053886070
Recommendation_3    6811309310070
Recommendation_4    6850090991734
Recommendation_5    6612902346870
Name: S5AdOaNmpdO2, dtype: int64
